services:
  node:
    build: "."
    command: npm run start:dev
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/app
    depends_on:
      - pgsql
    container_name: "node"

  pgsql:
    image: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5001:5432"
    container_name: "pgsql"

volumes:
  pgdata:
